[package]
name = "stock"
version = "0.1.0"
authors = ["yudhiesh1997 <yudhiesh1997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
